
export default constants = {
  REPLACE_TODOS: "REPLACE_TODOS",
  ADD_TODO: "ADD_TODO",
  TOOGLE_TODO: "TOOGLE_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  SELECT_TODO: "SELECT_TODO",
  EDIT_TODO: "EDIT_TODO",
  FILTER_TODO: "FILTER_TODO",
  TOOGLE_LOADING: "TOOGLE_LOADING",
  NO_ACTION: "NO_ACTION"
}